# Permission-allowlist voor Claude Code.
# Overgenomen uit ~/.claude/settings.json; eenmalige `git commit -m "<volledige
# message>"` literals zijn weggelaten omdat die nooit opnieuw matchen.
[
  "Bash(./result/bin/ssmsh:*)"
  "Bash(/data/scripts/fix-firefox-audio.sh:*)"
  "Bash(/dev/null sleep:*)"
  "Bash(/dev/null true:*)"
  "Bash(/dev/null which musescore)"
  "Bash(/dev/null:*)"
  "Bash(/nix/store/gv4kp09avjmap3whqi9raycbps4zfarf-ssmsh-v1.5.2/bin/ssmsh:*)"
  "Bash(/nix/store/i73iwp5a5nk8hjwx9hyidks4f8766m9z-tmux-3.6a/bin/tmux:*)"
  "Bash(/run/current-system/sw/bin/ssmsh:*)"
  "Bash(/usr/bin/env ps:*)"
  "Bash(AWS_PROFILE=IIT-Improvement-IT ./parsh:*)"
  "Bash(AWS_PROFILE=TN-NonProduction aws ssm:*)"
  "Bash(AWS_PROFILE=TN-Production aws ssm:*)"
  "Bash(AWS_PROFILE=technative aws ssm:*)"
  "Bash(AWS_PROFILE=technative terraform apply:*)"
  "Bash(AWS_PROFILE=technative terraform import:*)"
  "Bash(AWS_PROFILE=technative terraform init:*)"
  "Bash(AWS_PROFILE=technative terraform plan:*)"
  "Bash(DISPLAY=:0 XAUTHORITY=/run/user/1000/.mutter-Xwaylandauth.PM58O3 xdpyinfo)"
  "Bash(DISPLAY=:0 XAUTHORITY=/run/user/1000/.mutter-Xwaylandauth.PM58O3 xprop -root _NET_SUPPORTED)"
  "Bash(DISPLAY=:0 XAUTHORITY=/run/user/1000/.mutter-Xwaylandauth.PM58O3 xrandr)"
  "Bash(DISPLAY=:0 vim --version)"
  "Bash(DISPLAY=:0 wmctrl -l)"
  "Bash(DISPLAY=:0 wmctrl -lG)"
  "Bash(DISPLAY=:0 xdpyinfo)"
  "Bash(DISPLAY=:0 xlsclients)"
  "Bash(DISPLAY=:0 xprop -id 0xa00012)"
  "Bash(DISPLAY=:0 xprop -root _NET_CLIENT_LIST)"
  "Bash(DISPLAY=:0 xprop -root)"
  "Bash(DISPLAY=:0 xwininfo:*)"
  "Bash(DISPLAY=:1024 xdpyinfo)"
  "Bash(ELECTRON_OZONE_PLATFORM_HINT=wayland NIXOS_OZONE_WL=1 timeout:*)"
  "Bash(QT_DEBUG_PLUGINS=1 timeout 3 clementine:*)"
  "Bash(QT_DEBUG_PLUGINS=1 timeout 5 clementine:*)"
  "Bash(QT_QPA_PLATFORM=wayland subtitleedit:*)"
  "Bash(QT_QPA_PLATFORM=xcb QT_DEBUG_PLUGINS=1 timeout 5 clementine)"
  "Bash(QT_QPA_PLATFORM=xcb onlyoffice-desktopeditors --geometry=default)"
  "Bash(QT_QPA_PLATFORM=xcb onlyoffice-desktopeditors --help)"
  "Bash(QT_QPA_PLATFORM=xcb onlyoffice-desktopeditors)"
  "Bash(XAUTHORITY=/run/user/1000/.mutter-Xwaylandauth.9MVOP3 DISPLAY=:0 nix-shell -p xorg.xwininfo --run \"xwininfo -root -tree 2>&1 | head -10\")"
  "Bash(agenix -d grafana-dashboard-ssl.age -i /home/wtoorren/.ssh/improvement_it-awsaccount-workload-iit-key)"
  "Bash(agenix -d grafana-dashboard-ssl.age -i /home/wtoorren/.ssh/toorren-lobos-ed25519.backup)"
  "Bash(agenix -d grafana-dashboard-ssl.age -i ~/.ssh/id_ed25519)"
  "Bash(alacritty --version)"
  "Bash(amixer:*)"
  "Bash(appimage-run ~/.cache/appimage-run/84acf43c2e6fb3813524554057e24c907d70e0b7fe4997891a0c90c55d3d279b/bambu-studio.appimage)"
  "Bash(atuin:*)"
  "Bash(awk '{print $1}')"
  "Bash(aws ssm:*)"
  "Bash(bambu-studio)"
  "Bash(bash /data/scripts/fix-firefox-audio.sh)"
  "Bash(bash docker-run.sh)"
  "Bash(bmc --help)"
  "Bash(bmc console:*)"
  "Bash(busctl:*)"
  "Bash(cat /nix/store/s6wfpi2ssaaar9p8js4rn09zfpvpc0iy-aws-config-wtoorren)"
  "Bash(cat ~/.aws/config)"
  "Bash(cat ~/.aws/managed_service_accounts.json)"
  "Bash(cat:*)"
  "Bash(chmod +x ~/bin/screenshot-to-file)"
  "Bash(chmod:*)"
  "Bash(claude --version)"
  "Bash(clementine:*)"
  "Bash(command bmc:*)"
  "Bash(compgen:*)"
  "Bash(curl -s https://api.github.com/repos/bambulab/BambuStudio/releases/latest)"
  "Bash(curl:*)"
  "Bash(dbus-send:*)"
  "Bash(dconf dump:*)"
  "Bash(dconf list:*)"
  "Bash(dconf read:*)"
  "Bash(dconf reset:*)"
  "Bash(dconf write:*)"
  "Bash(dig -x 146.112.61.106)"
  "Bash(dig @1.1.1.1 boaz.toorren.net)"
  "Bash(dig @208.67.222.123 boaz.toorren.net)"
  "Bash(dig @208.67.222.123 toorren.net)"
  "Bash(dig boaz.toorren.net)"
  "Bash(dig toorren.net)"
  "Bash(dig:*)"
  "Bash(dmesg:*)"
  "Bash(do echo \"=== Boot -$i ===\")"
  "Bash(do echo:*)"
  "Bash(docker context:*)"
  "Bash(done)"
  "Bash(echo $WAYLAND_DISPLAY)"
  "Bash(echo $XDG_SESSION_TYPE)"
  "Bash(echo $fpath)"
  "Bash(echo \"SSH_CONNECTION: $SSH_CONNECTION\")"
  "Bash(echo \"Test: $WAYLAND_DISPLAY en $DISPLAY\")"
  "Bash(echo:*)"
  "Bash(find:*)"
  "Bash(flatpak info:*)"
  "Bash(flatpak install -y flathub com.bambulab.BambuStudio)"
  "Bash(flatpak list --app)"
  "Bash(flatpak list)"
  "Bash(flatpak override:*)"
  "Bash(flatpak permissions:*)"
  "Bash(flatpak run:*)"
  "Bash(flatpak uninstall -y com.bambulab.BambuStudio)"
  "Bash(flatpak uninstall -y com.bambulab.BambuStudio.Locale)"
  "Bash(for auth:*)"
  "Bash(for i in {0..10})"
  "Bash(gdbus call:*)"
  "Bash(gdbus introspect:*)"
  "Bash(gh api *)"
  "Bash(gh auth:*)"
  "Bash(gh pr:*)"
  "Bash(gh repo view:*)"
  "Bash(gh run view:*)"
  "Bash(git -C /home/wtoorren/data/git/torreirow/torreirow-nixos add configuration.nix flake.lock flake.nix hosts/lobos/gnome-wayland.nix hosts/lobos/programs.nix hosts/malandro/programs.nix overlays/default.nix)"
  "Bash(git -C /home/wtoorren/data/git/torreirow/torreirow-nixos add flake.nix home/zsh.nix overlays/default.nix openspec/changes/fix-quarto-pandoc-incompatibility/)"
  "Bash(git -C /home/wtoorren/data/git/torreirow/torreirow-nixos commit -m ' *)"
  "Bash(git -C /home/wtoorren/data/git/torreirow/torreirow-nixos commit -m 'chore: archiveer fix-quarto-pandoc-incompatibility change')"
  "Bash(git -C /home/wtoorren/data/git/torreirow/torreirow-nixos log --oneline -10)"
  "Bash(git -C /home/wtoorren/data/git/torreirow/torreirow-nixos push)"
  "Bash(git -C /home/wtoorren/data/git/torreirow/torreirow-nixos show 212ea92 --stat)"
  "Bash(git add home/gnome-desktop/default.nix home/gnome-desktop/wayland-fixes.nix hosts/lobos/configuration.nix WAYLAND_FIXES_2026-01-26.md)"
  "Bash(git add:*)"
  "Bash(git branch:*)"
  "Bash(git checkout:*)"
  "Bash(git clone:*)"
  "Bash(git commit:*)"
  "Bash(git diff:*)"
  "Bash(git fetch:*)"
  "Bash(git log:*)"
  "Bash(git push:*)"
  "Bash(git rebase:*)"
  "Bash(git reset:*)"
  "Bash(git restore:*)"
  "Bash(git rm:*)"
  "Bash(git show:*)"
  "Bash(git stash:*)"
  "Bash(git tag:*)"
  "Bash(gnome-extensions disable:*)"
  "Bash(gnome-extensions enable:*)"
  "Bash(gnome-extensions info clipboard-history@alexsaveau.dev)"
  "Bash(gnome-extensions info clipboard-indicator@tudmotu.com)"
  "Bash(gnome-extensions info focus-changer@heartmire)"
  "Bash(gnome-extensions info:*)"
  "Bash(gnome-extensions list *)"
  "Bash(gnome-extensions list --enabled)"
  "Bash(gnome-extensions list)"
  "Bash(gnome-session-quit:*)"
  "Bash(gnome-shell --version)"
  "Bash(gpaste-client get-history:*)"
  "Bash(grep:*)"
  "Bash(gsettings get org.gnome.desktop.interface scaling-factor)"
  "Bash(gsettings get org.gnome.mutter center-new-windows)"
  "Bash(gsettings get org.gnome.mutter experimental-features)"
  "Bash(gsettings get org.gnome.shell.extensions.clipboard-indicator cache-only-favorites)"
  "Bash(gsettings get:*)"
  "Bash(gsettings list-keys *)"
  "Bash(gsettings list-recursively:*)"
  "Bash(gsettings list-schemas:*)"
  "Bash(gsettings set org.gnome.mutter experimental-features \"[]\")"
  "Bash(gsettings set:*)"
  "Bash(hash:*)"
  "Bash(home-manager generations:*)"
  "Bash(home-manager switch:*)"
  "Bash(ip addr:*)"
  "Bash(ip link:*)"
  "Bash(journalctl --user -u org.gnome.Shell.desktop -b)"
  "Bash(journalctl -b -0)"
  "Bash(journalctl:*)"
  "Bash(kill:*)"
  "Bash(killall:*)"
  "Bash(ldd:*)"
  "Bash(loginctl enable-linger:*)"
  "Bash(loginctl list-sessions:*)"
  "Bash(loginctl lock-session:*)"
  "Bash(loginctl show-user:*)"
  "Bash(ls:*)"
  "Bash(lsblk:*)"
  "Bash(lsof:*)"
  "Bash(mkdir -p ~/data/git/technative)"
  "Bash(mscore --version:*)"
  "Bash(msmtp --debug wtoorren@gmail.com)"
  "Bash(mutter --version:*)"
  "Bash(nh os switch)"
  "Bash(nix build:*)"
  "Bash(nix eval --impure --expr 'let json_path = /home/wtoorren/.aws/managed_service_accounts.json; in if builtins.pathExists json_path then builtins.length (builtins.fromJSON (builtins.readFile json_path)) else 0')"
  "Bash(nix eval:*)"
  "Bash(nix flake check --show-trace)"
  "Bash(nix flake check:*)"
  "Bash(nix flake metadata github:NixOS/nixpkgs/nixos-24.11)"
  "Bash(nix flake metadata:*)"
  "Bash(nix search nixpkgs ^webkitgtk --json)"
  "Bash(nix search nixpkgs orca)"
  "Bash(nix search nixpkgs orcaslicer --json)"
  "Bash(nix search nixpkgs webkitgtk --json)"
  "Bash(nix search:*)"
  "Bash(nix store diff-closures:*)"
  "Bash(nix why-depends:*)"
  "Bash(nix-build:*)"
  "Bash(nix-collect-garbage)"
  "Bash(nix-env:*)"
  "Bash(nix-hash --to-sri --type sha256 16r77mfwb40c3a4rfjgynzh70zch9ki5fh2m4hsq3cvg5qyg9b44)"
  "Bash(nix-instantiate --eval -E 'builtins.hasAttr \"\"\"\"bookstack\"\"\"\" \\(import <nixpkgs> {}\\).services')"
  "Bash(nix-instantiate:*)"
  "Bash(nix-locate:*)"
  "Bash(nix-prefetch-github:*)"
  "Bash(nix-prefetch-url https://github.com/bambulab/BambuStudio/releases/download/v02.01.01.62/Bambu_Studio_linux_ubuntu_v02.01.01.62.AppImage)"
  "Bash(nix-prefetch-url https://github.com/bambulab/BambuStudio/releases/download/v02.04.00.70/Bambu_Studio_linux_fedora-v02.04.00.70.AppImage)"
  "Bash(nix-prefetch-url:*)"
  "Bash(nix-shell -p glib --run \"gresource list /nix/store/f4xr4fx4avglddkv3n76n8hk9g6h5q4c-gnome-shell-49.4/share/gnome-shell/org.gnome.Extensions.src.gresource 2>/dev/null | head -5\")"
  "Bash(nix-shell -p xorg.xclock --run \"xclock &\" 2)"
  "Bash(nix-shell:*)"
  "Bash(nix-store --query --references:*)"
  "Bash(nix-store:*)"
  "Bash(nix:*)"
  "Bash(nixos-rebuild list-generations:*)"
  "Bash(nixos-version:*)"
  "Bash(nmcli connection show:*)"
  "Bash(nmcli device:*)"
  "Bash(node -e \":*)"
  "Bash(nvim:*)"
  "Bash(objdump -d /nix/store/f4xr4fx4avglddkv3n76n8hk9g6h5q4c-gnome-shell-49.4/lib/gnome-shell/libshell-17.so)"
  "Bash(objdump -d /nix/store/v3glir7xy15x47irhgysxcwnghn1453i-systemd-minimal-libs-258.5/lib/libsystemd.so.0)"
  "Bash(objdump -d /nix/store/zy6fc2qvmjn4zw5nfpjm70zygf7f52kc-mutter-49.4/lib/libmutter-17.so.0)"
  "Bash(objdump -s --section=.rodata /nix/store/zy6fc2qvmjn4zw5nfpjm70zygf7f52kc-mutter-49.4/lib/libmutter-17.so.0)"
  "Bash(onlyoffice-desktopeditors:*)"
  "Bash(openspec --help:*)"
  "Bash(openspec archive --help:*)"
  "Bash(openspec archive:*)"
  "Bash(openspec change *)"
  "Bash(openspec create *)"
  "Bash(openspec instructions:*)"
  "Bash(openspec list:*)"
  "Bash(openspec new:*)"
  "Bash(openspec status:*)"
  "Bash(pactl info:*)"
  "Bash(pactl list:*)"
  "Bash(pactl set-source-volume:*)"
  "Bash(pgrep -f orca-slicer)"
  "Bash(pgrep:*)"
  "Bash(pkill -9 -f bambu)"
  "Bash(pkill -9 appimage-run)"
  "Bash(pkill -9 bambu)"
  "Bash(pkill -9 bambu-studio)"
  "Bash(pkill -9 bwrap)"
  "Bash(pkill -9 orca-slicer)"
  "Bash(pkill:*)"
  "Bash(printenv)"
  "Bash(pw-cli dump:*)"
  "Bash(pw-cli list-objects:*)"
  "Bash(pw-dump)"
  "Bash(pw-metadata:*)"
  "Bash(python3 -c \"print\\(open\\(''/proc/1/cgroup''\\).read\\(\\)\\)\")"
  "Bash(python3 -c \"print\\(open\\(''/proc/self/cgroup''\\).read\\(\\)\\)\")"
  "Bash(python3:*)"
  "Bash(qdbus-qt5:*)"
  "Bash(qdbus:*)"
  "Bash(quarto --version)"
  "Bash(readelf:*)"
  "Bash(readlink -f ~/.aws/config)"
  "Bash(readlink -f ~/.config/home-manager/home.nix)"
  "Bash(readlink:*)"
  "Bash(rm -rf /home/wtoorren/.local/share/gnome-shell/extensions/focus-changer@heartmire)"
  "Bash(rm -rf /home/wtoorren/.local/share/gnome-shell/extensions/launcher@hedgie.tech)"
  "Bash(rm -rf /home/wtoorren/.local/share/gnome-shell/extensions/useless-gaps@pimsnel.com)"
  "Bash(rm -rf /home/wtoorren/.local/share/gnome-shell/extensions/window-on-top@yousafesaeed.github.io)"
  "Bash(rtk proxy:*)"
  "Bash(secret-tool search:*)"
  "Bash(smug --help)"
  "Bash(smug list *)"
  "Bash(smug start *)"
  "Bash(spg --help)"
  "Bash(sqlite3:*)"
  "Bash(ssh-keygen -y -f /home/wtoorren/.ssh/technative-awsaccounts-workloads-key)"
  "Bash(ssh-keygen -y -f /home/wtoorren/.ssh/toorren-lobos-ed25519.backup)"
  "Bash(ssh-add:*)"
  "Bash(ssh:*)"
  "Bash(ssmsh:*)"
  "Bash(strace:*)"
  "Bash(sudo /nix/store/rlvpzq74xz13gxpdsnz47v9xhd29028j-nixos-system-malandro-25.11.20260314.e9f278f/bin/switch-to-configuration:*)"
  "Bash(sudo /nix/var/nix/profiles/system/bin/switch-to-configuration:*)"
  "Bash(sudo cat:*)"
  "Bash(sudo chmod:*)"
  "Bash(sudo dmesg:*)"
  "Bash(sudo dmidecode:*)"
  "Bash(sudo journalctl:*)"
  "Bash(sudo ln:*)"
  "Bash(sudo ls -la /var/lib/wg-easy)"
  "Bash(sudo nix-env:*)"
  "Bash(sudo nixos-rebuild switch:*)"
  "Bash(sudo nixos-rebuild:*)"
  "Bash(sudo nsenter:*)"
  "Bash(sudo reboot:*)"
  "Bash(sudo resolvectl:*)"
  "Bash(sudo sh -c \"echo deep > /sys/power/mem_sleep\")"
  "Bash(sudo systemctl:*)"
  "Bash(sudo systemd-cgls:*)"
  "Bash(sudo systemd-resolve:*)"
  "Bash(sudo tee:*)"
  "Bash(systemctl --user status aws-accounts-sync.service)"
  "Bash(systemctl status:*)"
  "Bash(systemctl:*)"
  "Bash(systemd --version)"
  "Bash(systemd-inhibit:*)"
  "Bash(tar -tJf /nix/store/p2bhrgizljjj3brrwvdzbh72rsvjdmn0-SalamanderGrandPiano-SF2-V3+20200602.tar.xz)"
  "Bash(tar -tz)"
  "Bash(tee:*)"
  "Bash(timeout 10 flatpak run:*)"
  "Bash(timeout 3 bambu-studio)"
  "Bash(timeout 5 clementine:*)"
  "Bash(timeout 5 strace:*)"
  "Bash(timeout 8 clementine:*)"
  "Bash(timeout:*)"
  "Bash(tmux attach:*)"
  "Bash(tmux ls:*)"
  "Bash(tmux show-options -g)"
  "Bash(tmux source-file:*)"
  "Bash(tmux:*)"
  "Bash(vim --version)"
  "Bash(vim:*)"
  "Bash(vlc --version)"
  "Bash(whois 146.112.61.106)"
  "Bash(wl-copy:*)"
  "Bash(wl-paste:*)"
  "Bash(wmctrl:*)"
  "Bash(wpctl get-volume:*)"
  "Bash(wpctl inspect:*)"
  "Bash(wpctl set-default:*)"
  "Bash(wpctl set-mute:*)"
  "Bash(wpctl set-profile:*)"
  "Bash(wpctl set-volume:*)"
  "Bash(wpctl status:*)"
  "Bash(xargs readlink:*)"
  "Bash(xargs:*)"
  "Bash(xdotool search --class bambu-studio)"
  "Bash(xdotool search --class bitwarden)"
  "Bash(xdotool search --name Bambu)"
  "Bash(xdotool search --name \"Bambu Studio\")"
  "Bash(xdotool search:*)"
  "Bash(xdpyinfo)"
  "Bash(xprop -id 0x80001f)"
  "Bash(xprop -root _NET_ACTIVE_WINDOW)"
  "Bash(xprop -root _NET_CLIENT_LIST)"
  "Bash(xrandr --output HDMI-1 --off)"
  "Bash(xrandr)"
  "Bash(xwininfo:*)"
  "Bash(xxd:*)"
  "Bash(zsh -c 'echo \"\"Zsh werkt correct! ZSH path: $ZSH\"\"')"
  "Bash(zsh -c 'print -l \${(k)_comps}')"
  "Bash(~/bin/screenshot-to-file)"
  "Bash(~/go/bin/ssmsh:*)"
  "Read(//etc/gdm/**)"
  "Read(//home/wtoorren/.local/share/gnome-shell/extensions/**)"
  "Read(//home/wtoorren/.local/state/wireplumber/**)"
  "Read(//nix/store/z8v7vcmxgkz1clwsx3ynzbn5cxy3zi3b-hyprland-0.55.2/share/wayland-sessions/**)"
  "Read(//proc/**)"
  "Read(//proc/240139/**)"
  "Read(//run/**)"
  "WebFetch(domain:api.github.com)"
  "WebFetch(domain:beresolute.org)"
  "WebFetch(domain:claude.ai)"
  "WebFetch(domain:domain.opendns.com)"
  "WebFetch(domain:extensions.gnome.org)"
  "WebFetch(domain:github.com)"
  "WebFetch(domain:gitlab.gnome.org)"
  "WebFetch(domain:nix.catppuccin.com)"
  "WebFetch(domain:nixos.org)"
  "WebFetch(domain:raw.githubusercontent.com)"
  "WebFetch(domain:release.gnome.org)"
  "WebFetch(domain:search.nixos.org)"
  "WebFetch(domain:wiki.hypr.land)"
  "WebFetch(domain:www.bright.fm)"
  "WebSearch"
]
