{ lib, pkgs, config, ... }:

let
  # Read SSH hosts configuration from JSON file
  ssh_hosts_file = "${config.home.homeDirectory}/data/git/torreirow/torreirow-nixos/home/ssh-hosts.json";
  ssh_hosts = builtins.fromJSON (lib.readFile ssh_hosts_file);

  # Path where rbw SSH keys are exported (as .pub files)
  ssh_keys_dir = "${config.home.homeDirectory}/.ssh/rbw-keys";

  # Generate SSH config entry for a single host
  generateHostEntry = host:
    let
      # Extract identity file name (remove .pub extension if present)
      identity_name =
        if lib.hasSuffix ".pub" host.identity_file
        then lib.removeSuffix ".pub" host.identity_file
        else host.identity_file;

      # Build the identity file path
      identity_path = "${ssh_keys_dir}/${identity_name}";

      # Optional fields
      hostnameField = lib.optionalString (host ? hostname) "  HostName ${host.hostname}\n";
      userField = lib.optionalString (host ? user) "  User ${host.user}\n";
      portField = lib.optionalString (host ? port && host.port != 22) "  Port ${toString host.port}\n";
    in
    ''
      Host ${host.host}
      ${hostnameField}${userField}${portField}  IdentityFile ${identity_path}
        IdentitiesOnly yes
    '';

  # Generate all SSH config entries
  sshConfigContent = lib.concatMapStringsSep "\n" generateHostEntry ssh_hosts;

  # Full config file with header
  configFileContent = ''
    # Generated by NixOS Home Manager
    # Source: ~/data/git/torreirow/torreirow-nixos/home/ssh-config_hosts.nix
    # Input: ~/data/git/torreirow/torreirow-nixos/home/ssh-hosts.json
    #
    # SSH keys are managed by rbw (Bitwarden CLI)
    # Key files should be exported to ${ssh_keys_dir}
    #
    # To update SSH keys, run:
    #   cd ${ssh_keys_dir} && ${config.home.homeDirectory}/bin/export-ssh-keys.sh

    ${sshConfigContent}
  '';

in
{
  # Ensure the rbw-keys directory exists
  home.file."${ssh_keys_dir}/.keep".text = "";

  # Generate ~/.ssh/config.d/rbw.conf
  home.file.".ssh/config.d/rbw.conf" = {
    text = configFileContent;
    onChange = ''
      # Verify SSH config syntax after changes
      ${pkgs.openssh}/bin/ssh -G localhost > /dev/null 2>&1 || {
        echo "Warning: SSH config syntax error detected in rbw.conf"
      }
    '';
  };

  # Ensure main SSH config includes config.d directory
  programs.ssh = {
    enable = true;
    includes = [
      "~/.ssh/config.d/*.conf"
    ];
  };

  # Add a convenient script to export SSH keys from rbw
  home.file."bin/export-ssh-keys.sh" = {
    executable = true;
    text = builtins.readFile /tmp/ssh/export-ssh-keys-v5.sh;
  };

  # Environment variable to help scripts find the SSH keys directory
  home.sessionVariables = {
    RBW_SSH_KEYS_DIR = ssh_keys_dir;
  };
}
