{
 "title": "HTTP-check",
 "tags": [
  "blackbox",
  "http",
  "status"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_http_status_code{job=\"blackbox-technative\"})"
    }
   ]
  },
  {
   "title": "200 OK",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_http_status_code{job=\"blackbox-technative\"} == 200)"
    }
   ]
  },
  {
   "title": "500 Server Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_http_status_code{job=\"blackbox-technative\"} == 500)"
    }
   ]
  },
  {
   "title": "404 Not Found",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_http_status_code{job=\"blackbox-technative\"} == 404)"
    }
   ]
  },
  {
   "title": "301/302 Redirects",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_http_status_code{job=\"blackbox-technative\"} == 301) + count(probe_http_status_code{job=\"blackbox-technative\"} == 302)"
    }
   ]
  },
  {
   "title": "Other Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_http_status_code{job=\"blackbox-technative\"} != 200\nand probe_http_status_code{job=\"blackbox-technative\"} != 301\nand probe_http_status_code{job=\"blackbox-technative\"} != 302\nand probe_http_status_code{job=\"blackbox-technative\"} != 404\nand probe_http_status_code{job=\"blackbox-technative\"} != 500)\n"
    }
   ]
  },
  {
   "title": "URLs in Error",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"blackbox-technative\"} != 200",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}