{
 "title": "TechNative - HTTP & SSL Monitoring",
 "tags": [
  "blackbox",
  "http",
  "ssl",
  "technative",
  "iac"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "HTTP Checks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_http_status_code{job=\"blackbox-technative\"})"
    }
   ]
  },
  {
   "title": "200 OK",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_http_status_code{job=\"blackbox-technative\"} == 200)"
    }
   ]
  },
  {
   "title": "500 Server Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_http_status_code{job=\"blackbox-technative\"} == 500)"
    }
   ]
  },
  {
   "title": "404 Not Found",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_http_status_code{job=\"blackbox-technative\"} == 404)"
    }
   ]
  },
  {
   "title": "301/302 Redirects",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_http_status_code{job=\"blackbox-technative\"} == 301) + count(probe_http_status_code{job=\"blackbox-technative\"} == 302)"
    }
   ]
  },
  {
   "title": "Other Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_http_status_code{job=\"blackbox-technative\"} != 200\nand probe_http_status_code{job=\"blackbox-technative\"} != 301\nand probe_http_status_code{job=\"blackbox-technative\"} != 302\nand probe_http_status_code{job=\"blackbox-technative\"} != 404\nand probe_http_status_code{job=\"blackbox-technative\"} != 500)"
    }
   ]
  },
  {
   "title": "URLs in Error",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"blackbox-technative\"} != 200"
    }
   ]
  },
  { "title": "SSL Certificate Expiry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "SSL Certificate Expiry (Days Left)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "(probe_ssl_earliest_cert_expiry{job=\"blackbox-technative\"} - time()) / 86400",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}