{ lib, pkgs, config, ... }:

with lib;

let
  cfg = config.programs.ssh-config-hosts;

  # Base directory for this module - use relative path from module location
  module_dir = ./.;
  hosts_dir = "${module_dir}/hosts";

  # Automatically discover all .json files in the hosts directory
  discoverJsonFiles = dir:
    let
      # List all entries in the directory
      entries = builtins.readDir dir;

      # Filter for .json files only
      jsonFiles = lib.filterAttrs (name: type:
        type == "regular" && lib.hasSuffix ".json" name
      ) entries;

      # Convert to list of full paths
      jsonPaths = lib.mapAttrsToList (name: _: "${dir}/${name}") jsonFiles;
    in
    jsonPaths;

  # Get all JSON configuration files from hosts directory
  local_json_files = discoverJsonFiles hosts_dir;

  # Path where rbw SSH keys are exported (as .pub files)
  ssh_keys_dir = "${config.home.homeDirectory}/.ssh/rbw-keys";

  # Generate SSH config entry for a single host
  generateHostEntry = host:
    let
      # Extract identity file name (remove .pub extension if present)
      identity_name =
        if lib.hasSuffix ".pub" host.identity_file
        then lib.removeSuffix ".pub" host.identity_file
        else host.identity_file;

      # Build the identity file path
      identity_path = "${ssh_keys_dir}/${identity_name}";

      # Optional fields
      hostnameField = lib.optionalString (host ? hostname) "  HostName ${host.hostname}\n";
      userField = lib.optionalString (host ? user) "  User ${host.user}\n";
      portField = lib.optionalString (host ? port && host.port != 22) "  Port ${toString host.port}\n";
    in
    ''
      Host ${host.host}
      ${hostnameField}${userField}${portField}  IdentityFile ${identity_path}
        IdentitiesOnly yes
    '';

  # Read and parse each JSON file (only for local files at evaluation time)
  readHostsFile = file:
    let
      content = builtins.readFile file;
      parsed = builtins.fromJSON content;
    in
    if builtins.isList parsed
    then parsed
    else [];

  # Generate config content for a single local JSON file
  generateConfigForFile = jsonFile:
    let
      hosts = readHostsFile jsonFile;
      fileName = builtins.unsafeDiscardStringContext (lib.removeSuffix ".json" (builtins.baseNameOf jsonFile));
      sourceComment = lib.removePrefix hosts_dir jsonFile;
      sshConfigContent = lib.concatMapStringsSep "\n" generateHostEntry hosts;
    in
    {
      name = ".ssh/config.d/rbw-${fileName}.conf";
      value = {
        text = ''
          # Generated by NixOS Home Manager
          # Source: ${sourceComment}
          # Module: ~/data/git/torreirow/torreirow-nixos/home/module/ssh-config_hosts/default.nix
          #
          # SSH keys are managed by rbw (Bitwarden CLI)
          # Key files are exported to ${ssh_keys_dir}
          #
          # To update SSH keys, run:
          #   ${config.home.homeDirectory}/bin/export-ssh-keys.sh

          ${sshConfigContent}
        '';
        onChange = ''
          # Verify SSH config syntax after changes
          ${pkgs.openssh}/bin/ssh -G localhost > /dev/null 2>&1 || {
            echo "Warning: SSH config syntax error detected in rbw-${fileName}.conf"
          }
        '';
      };
    };

  # Generate all config files for local JSON files
  sshConfigFiles = builtins.listToAttrs (map generateConfigForFile local_json_files);

  # Script to generate SSH config from agenix secrets at activation time
  generateAgenixConfigScript = pkgs.writeShellScript "generate-agenix-ssh-configs" ''
    set -euo pipefail

    SSH_KEYS_DIR="${ssh_keys_dir}"
    CONFIG_DIR="${config.home.homeDirectory}/.ssh/config.d"

    # Process a single agenix secret JSON file
    process_secret() {
      local name="$1"
      local path="$2"
      local output_file="$CONFIG_DIR/rbw-$name.conf"

      # Check if file exists
      if [ ! -f "$path" ]; then
        echo "Warning: Agenix secret not found: $path (skipping $name)"
        return 0
      fi

      # Check if file is readable
      if [ ! -r "$path" ]; then
        echo "Warning: Agenix secret not readable: $path (skipping $name)"
        return 0
      fi

      echo "Processing agenix secret: $name"

      # Validate JSON before processing
      if ! ${pkgs.jq}/bin/jq -e '.' "$path" > /dev/null 2>&1; then
        echo "Warning: Invalid JSON in agenix secret: $path (skipping $name)"
        return 0
      fi

      # Generate config file
      {
        echo "# Generated by NixOS Home Manager (activation script)"
        echo "# Source: agenix secret (encrypted)"
        echo "# Module: ~/data/git/torreirow/torreirow-nixos/home/module/ssh-config_hosts/default.nix"
        echo "#"
        echo "# SSH keys are managed by rbw (Bitwarden CLI)"
        echo "# Key files are exported to $SSH_KEYS_DIR"
        echo "#"
        echo "# To update SSH keys, run:"
        echo "#   ${config.home.homeDirectory}/bin/export-ssh-keys.sh"
        echo ""

        # Parse JSON and generate entries using jq to format each host directly
        ${pkgs.jq}/bin/jq -r '.[] | "Host \(.host)\n" + (if .hostname then "  HostName \(.hostname)\n" else "" end) + (if .user then "  User \(.user)\n" else "" end) + (if .port and .port != 22 then "  Port \(.port)\n" else "" end) + "  IdentityFile '"$SSH_KEYS_DIR"'/\(.identity_file | sub("\\.pub$"; ""))\n    IdentitiesOnly yes\n"' "$path"
      } > "$output_file"

      chmod 600 "$output_file"
      echo "Generated: $output_file"
    }

    # Ensure config directory exists
    mkdir -p "$CONFIG_DIR"

    # Process each configured agenix secret
    ${lib.concatMapStringsSep "\n" (secret: ''
      process_secret "${secret.name}" "${secret.path}"
    '') cfg.agenixSecrets}

    echo "Agenix SSH config generation complete"
  '';

in
{
  options.programs.ssh-config-hosts = {
    agenixSecrets = mkOption {
      type = types.listOf (types.submodule {
        options = {
          name = mkOption {
            type = types.str;
            description = "Name of the secret (used for config filename)";
            example = "customer-secret";
          };
          path = mkOption {
            type = types.str;
            description = "Path to the decrypted agenix secret file (as string to avoid pure eval issues)";
            example = "/run/secrets/ssh-hosts-customer-a";
          };
        };
      });
      default = [];
      description = ''
        List of agenix secrets containing SSH host configurations.
        Each secret should contain a JSON file in the same format as the local JSON files.

        These secrets are processed at activation time (not evaluation time),
        so they work correctly with agenix's runtime decryption.

        Example:
          In your NixOS configuration:
            age.secrets.ssh-hosts-customer-a = {
              file = ./secrets/ssh-hosts-customer-a.json.age;
              path = "/run/secrets/ssh-hosts-customer-a";
              owner = "wtoorren";
              mode = "0400";
            };

          In your home-manager configuration:
            programs.ssh-config-hosts.agenixSecrets = [{
              name = "customer-a";
              path = "/run/secrets/ssh-hosts-customer-a";
            }];
      '';
      example = literalExpression ''
        [{
          name = "customer-secret";
          path = "/run/secrets/ssh-hosts-customer-secret";
        }]
      '';
    };
  };

  config = {
    # Generate separate config files for each local JSON file
    home.file = sshConfigFiles // {
      # Ensure the rbw-keys directory exists
      "${ssh_keys_dir}/.keep".text = "";

      # Add a convenient script to export SSH keys from rbw
      "bin/export-ssh-keys.sh" = {
        executable = true;
        text = builtins.readFile "${module_dir}/export-ssh-keys.sh";
      };
    };

    # Activation script to generate SSH configs from agenix secrets at runtime
    home.activation.generateAgenixSshConfigs = lib.mkIf (cfg.agenixSecrets != []) (
      lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        run ${generateAgenixConfigScript}
      ''
    );

    # Ensure main SSH config includes config.d directory
    programs.ssh = {
      enable = true;
      includes = [
        "~/.ssh/config.d/*.conf"
      ];
    };

    # Environment variable to help scripts find the SSH keys directory
    home.sessionVariables = {
      RBW_SSH_KEYS_DIR = ssh_keys_dir;
    };
  };
}
