{ lib, pkgs, config, ... }:

with lib;

let
  cfg = config.programs.ssh-config-hosts;

  # Base directory for this module
  module_dir = "${config.home.homeDirectory}/data/git/torreirow/torreirow-nixos/home/module/ssh-config_hosts";
  hosts_dir = "${module_dir}/hosts";

  # Automatically discover all .json files in the hosts directory
  discoverJsonFiles = dir:
    let
      # List all entries in the directory
      entries = builtins.readDir dir;

      # Filter for .json files only
      jsonFiles = lib.filterAttrs (name: type:
        type == "regular" && lib.hasSuffix ".json" name
      ) entries;

      # Convert to list of full paths
      jsonPaths = lib.mapAttrsToList (name: _: "${dir}/${name}") jsonFiles;
    in
    jsonPaths;

  # Get all JSON configuration files from hosts directory
  local_json_files = discoverJsonFiles hosts_dir;

  # Convert agenix secrets to file paths
  agenix_json_files = map (secret: secret.path) cfg.agenixSecrets;

  # Combine local and agenix files
  ssh_config_files = local_json_files ++ agenix_json_files;

  # Read and parse each JSON file
  readHostsFile = file:
    let
      content = builtins.readFile file;
      parsed = builtins.fromJSON content;
    in
    if builtins.isList parsed
    then parsed
    else [];

  # Combine all host configurations from multiple JSON files
  ssh_hosts = lib.flatten (map readHostsFile ssh_config_files);

  # Path where rbw SSH keys are exported (as .pub files)
  ssh_keys_dir = "${config.home.homeDirectory}/.ssh/rbw-keys";

  # Generate SSH config entry for a single host
  generateHostEntry = host:
    let
      # Extract identity file name (remove .pub extension if present)
      identity_name =
        if lib.hasSuffix ".pub" host.identity_file
        then lib.removeSuffix ".pub" host.identity_file
        else host.identity_file;

      # Build the identity file path
      identity_path = "${ssh_keys_dir}/${identity_name}";

      # Optional fields
      hostnameField = lib.optionalString (host ? hostname) "  HostName ${host.hostname}\n";
      userField = lib.optionalString (host ? user) "  User ${host.user}\n";
      portField = lib.optionalString (host ? port && host.port != 22) "  Port ${toString host.port}\n";
    in
    ''
      Host ${host.host}
      ${hostnameField}${userField}${portField}  IdentityFile ${identity_path}
        IdentitiesOnly yes
    '';

  # Helper to determine if a file is from agenix
  isAgenixFile = jsonFile:
    lib.any (secret: secret.path == jsonFile) cfg.agenixSecrets;

  # Get the custom name for agenix secret, or derive from filename
  getFileName = jsonFile:
    let
      agenixSecret = lib.findFirst (secret: secret.path == jsonFile) null cfg.agenixSecrets;
    in
    if agenixSecret != null
    then agenixSecret.name
    else lib.removeSuffix ".json" (builtins.baseNameOf jsonFile);

  # Generate config content for a single JSON file
  generateConfigForFile = jsonFile:
    let
      hosts = readHostsFile jsonFile;
      fileName = getFileName jsonFile;
      sourceComment = if isAgenixFile jsonFile
        then "agenix secret (encrypted)"
        else lib.removePrefix hosts_dir jsonFile;
      sshConfigContent = lib.concatMapStringsSep "\n" generateHostEntry hosts;
    in
    {
      name = ".ssh/config.d/rbw-${fileName}.conf";
      value = {
        text = ''
          # Generated by NixOS Home Manager
          # Source: ${sourceComment}
          # Module: ~/data/git/torreirow/torreirow-nixos/home/module/ssh-config_hosts/default.nix
          #
          # SSH keys are managed by rbw (Bitwarden CLI)
          # Key files are exported to ${ssh_keys_dir}
          #
          # To update SSH keys, run:
          #   ${config.home.homeDirectory}/bin/export-ssh-keys.sh

          ${sshConfigContent}
        '';
        onChange = ''
          # Verify SSH config syntax after changes
          ${pkgs.openssh}/bin/ssh -G localhost > /dev/null 2>&1 || {
            echo "Warning: SSH config syntax error detected in rbw-${fileName}.conf"
          }
        '';
      };
    };

  # Generate all config files
  sshConfigFiles = builtins.listToAttrs (map generateConfigForFile ssh_config_files);

in
{
  options.programs.ssh-config-hosts = {
    agenixSecrets = mkOption {
      type = types.listOf (types.submodule {
        options = {
          name = mkOption {
            type = types.str;
            description = "Name of the secret (used for config filename)";
            example = "customer-secret";
          };
          path = mkOption {
            type = types.path;
            description = "Path to the decrypted agenix secret file";
            example = "/run/secrets/ssh-hosts-customer-a";
          };
        };
      });
      default = [];
      description = ''
        List of agenix secrets containing SSH host configurations.
        Each secret should contain a JSON file in the same format as the local JSON files.

        Example:
          In your NixOS configuration:
            age.secrets.ssh-hosts-customer-a = {
              file = ./secrets/ssh-hosts-customer-a.json.age;
              path = "/run/secrets/ssh-hosts-customer-a";
              owner = "wtoorren";
              mode = "0400";
            };

          In your home-manager configuration:
            programs.ssh-config-hosts.agenixSecrets = [{
              name = "customer-a";
              path = config.age.secrets.ssh-hosts-customer-a.path;
            }];
      '';
      example = literalExpression ''
        [{
          name = "customer-secret";
          path = config.age.secrets.ssh-hosts-customer-secret.path;
        }]
      '';
    };
  };

  config = {
    # Generate separate config files for each JSON file
    # This merges all generated config files into home.file
    home.file = sshConfigFiles // {
      # Ensure the rbw-keys directory exists
      "${ssh_keys_dir}/.keep".text = "";

      # Add a convenient script to export SSH keys from rbw
      "bin/export-ssh-keys.sh" = {
        executable = true;
        text = builtins.readFile "${module_dir}/export-ssh-keys.sh";
      };
    };

    # Ensure main SSH config includes config.d directory
    programs.ssh = {
      enable = true;
      includes = [
        "~/.ssh/config.d/*.conf"
      ];
    };

    # Environment variable to help scripts find the SSH keys directory
    home.sessionVariables = {
      RBW_SSH_KEYS_DIR = ssh_keys_dir;
    };
  };
}
