{ lib, pkgs, config, ... }:

let
  # Base directory for this module
  module_dir = "${config.home.homeDirectory}/data/git/torreirow/torreirow-nixos/home/module/ssh-config_hosts";
  hosts_dir = "${module_dir}/hosts";

  # Automatically discover all .json files in the hosts directory
  discoverJsonFiles = dir:
    let
      # List all entries in the directory
      entries = builtins.readDir dir;

      # Filter for .json files only
      jsonFiles = lib.filterAttrs (name: type:
        type == "regular" && lib.hasSuffix ".json" name
      ) entries;

      # Convert to list of full paths
      jsonPaths = lib.mapAttrsToList (name: _: "${dir}/${name}") jsonFiles;
    in
    jsonPaths;

  # Get all JSON configuration files
  ssh_config_files = discoverJsonFiles hosts_dir;

  # Read and parse each JSON file
  readHostsFile = file:
    let
      content = builtins.readFile file;
      parsed = builtins.fromJSON content;
    in
    if builtins.isList parsed
    then parsed
    else [];

  # Combine all host configurations from multiple JSON files
  ssh_hosts = lib.flatten (map readHostsFile ssh_config_files);

  # Path where rbw SSH keys are exported (as .pub files)
  ssh_keys_dir = "${config.home.homeDirectory}/.ssh/rbw-keys";

  # Generate SSH config entry for a single host
  generateHostEntry = host:
    let
      # Extract identity file name (remove .pub extension if present)
      identity_name =
        if lib.hasSuffix ".pub" host.identity_file
        then lib.removeSuffix ".pub" host.identity_file
        else host.identity_file;

      # Build the identity file path
      identity_path = "${ssh_keys_dir}/${identity_name}";

      # Optional fields
      hostnameField = lib.optionalString (host ? hostname) "  HostName ${host.hostname}\n";
      userField = lib.optionalString (host ? user) "  User ${host.user}\n";
      portField = lib.optionalString (host ? port && host.port != 22) "  Port ${toString host.port}\n";
    in
    ''
      Host ${host.host}
      ${hostnameField}${userField}${portField}  IdentityFile ${identity_path}
        IdentitiesOnly yes
    '';

  # Generate all SSH config entries
  sshConfigContent = lib.concatMapStringsSep "\n" generateHostEntry ssh_hosts;

  # List of loaded config files for documentation
  loadedFiles = lib.concatMapStringsSep "\n#   - "
    (f: lib.removePrefix hosts_dir f)
    ssh_config_files;

  # Full config file with header
  configFileContent = ''
    # Generated by NixOS Home Manager
    # Module: ~/data/git/torreirow/torreirow-nixos/home/module/ssh-config_hosts/default.nix
    #
    # Loaded configuration files from hosts/:
    #   - ${loadedFiles}
    #
    # SSH keys are managed by rbw (Bitwarden CLI)
    # Key files are exported to ${ssh_keys_dir}
    #
    # To update SSH keys, run:
    #   ${config.home.homeDirectory}/bin/export-ssh-keys.sh
    #
    # To add new hosts:
    #   1. Create a new .json file in: ${hosts_dir}
    #   2. Run: home-manager switch
    #   All .json files are automatically loaded!

    ${sshConfigContent}
  '';

in
{
  # Ensure the rbw-keys directory exists
  home.file."${ssh_keys_dir}/.keep".text = "";

  # Generate ~/.ssh/config.d/rbw.conf
  home.file.".ssh/config.d/rbw.conf" = {
    text = configFileContent;
    onChange = ''
      # Verify SSH config syntax after changes
      ${pkgs.openssh}/bin/ssh -G localhost > /dev/null 2>&1 || {
        echo "Warning: SSH config syntax error detected in rbw.conf"
      }
    '';
  };

  # Ensure main SSH config includes config.d directory
  programs.ssh = {
    enable = true;
    includes = [
      "~/.ssh/config.d/*.conf"
    ];
  };

  # Add a convenient script to export SSH keys from rbw
  home.file."bin/export-ssh-keys.sh" = {
    executable = true;
    text = builtins.readFile /tmp/ssh/export-ssh-keys-v5.sh;
  };

  # Environment variable to help scripts find the SSH keys directory
  home.sessionVariables = {
    RBW_SSH_KEYS_DIR = ssh_keys_dir;
  };
}
